import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#11121f",
        "error-container": "#93000a",
        "surface-variant": "#333442",
        "on-primary-fixed": "#002022",
        "surface-container-lowest": "#0c0d19",
        "surface-dim": "#11121f",
        "inverse-on-surface": "#2e2f3d",
        "on-primary": "#00373a",
        "on-secondary": "#3d0090",
        "tertiary-fixed-dim": "#ffafd4",
        "inverse-primary": "#00696f",
        tertiary: "#fff5f7",
        "on-background": "#e2e1f3",
        "primary-fixed-dim": "#00dce6",
        "on-primary-container": "#006a70",
        "primary-fixed": "#6ff6ff",
        "on-tertiary-fixed-variant": "#8a005d",
        "secondary-container": "#6900ec",
        "surface-container-low": "#1a1b27",
        "surface-tint": "#00dce6",
        primary: "#e0fdff",
        "outline-variant": "#3a494b",
        "secondary-fixed": "#eaddff",
        "tertiary-fixed": "#ffd8e7",
        "on-surface-variant": "#b9cacb",
        "surface-container-high": "#282936",
        "surface-container-highest": "#333442",
        "surface-bright": "#373846",
        "secondary-fixed-dim": "#d1bcff",
        "tertiary-container": "#ffcee2",
        "on-primary-fixed-variant": "#004f53",
        "on-tertiary-fixed": "#3d0027",
        outline: "#849495",
        "primary-container": "#00f2fe",
        "on-error": "#690005",
        secondary: "#d1bcff",
        "surface-container": "#1e1f2c",
        surface: "#11121f",
        "on-secondary-fixed": "#24005b",
        "inverse-surface": "#e2e1f3",
        "on-secondary-container": "#d4c0ff",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#5800c8",
        "on-tertiary-container": "#b8007d",
        "on-tertiary": "#620041",
        error: "#ffb4ab",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "space-md": "1rem",
        "gutter-mobile": "1rem",
        "space-lg": "1.5rem",
        "space-3xl": "4.5rem",
        "space-sm": "0.75rem",
        "space-2xl": "3rem",
        "space-xs": "0.5rem",
        "space-2xs": "0.25rem",
        "gutter-desktop": "1.75rem",
        "space-xl": "2rem",
        "container-max": "84rem",
      },
      fontFamily: {
        "body-sm": ["var(--font-hanken)", "sans-serif"],
        "headline-sm": ["var(--font-hanken)", "sans-serif"],
        "body-lg": ["var(--font-hanken)", "sans-serif"],
        "headline-md": ["var(--font-hanken)", "sans-serif"],
        display: ["var(--font-hanken)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-hanken)", "sans-serif"],
        "headline-lg": ["var(--font-hanken)", "sans-serif"],
        "label-sm": ["var(--font-geist)", "sans-serif"],
        "label-md": ["var(--font-geist)", "sans-serif"],
        "body-md": ["var(--font-hanken)", "sans-serif"],
        "display-mobile": ["var(--font-hanken)", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        display: ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "display-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "700" }],
      },
      keyframes: {
        "beam-fade": {
          "0%": { opacity: "0" },
          "5%": { opacity: "1" },
          "80%, 100%": { opacity: "0" },
        },
        "scroll-x": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-100%)" },
        },
        "scroll-x-reverse": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(0)" },
        },
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "spin-slow": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "beam-fade": "beam-fade 2s linear infinite",
        "scroll-x": "scroll-x var(--scroll-duration,40s) linear infinite",
        "scroll-x-reverse": "scroll-x-reverse var(--scroll-duration,40s) linear infinite",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "spin-slow": "spin-slow 4s linear infinite",
      },
    },
  },
  plugins: [],
};

export default config;
